[project]
name = "final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "pip>=25.3",
    "pydantic-ai>=1.25.1",
    "python-dotenv>=1.2.1",
    "requests>=2.31.0",
]
